id: P005597
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1PD105890
  title: བཀའ་བསྡུ་བཞི་པའི་དོན་བསྟན་རྩིས་ཆེན་པོ།
  author: ''
  volumes:
    c02c7f455d994f2ab628bb688231afe6:
      image_group_id: I1PD105892
      title: ''
      volume_number: 1
      total_pages: 224
      base_file: v001.txt
